### PR TITLE
Addadmin

### PR DESCRIPTION
**Pull request by 0486**
Review and Merge please.

### CODE REVIEW

**Comment by elpiankova** [comment]
We need to add Value and Units to Admin interface

**Comment by landswellsong** [comment]
Standard user: `promis`
Standard password: `swordfish`

**Comment by elpiankova** [comment]
We need add FK Satellite(Space_project) in Session table

**Comment by elpiankova** [comment]
Why is `description` in `__str__` methods of Space_project, Channel, Value and Parameter models instead of `name`?

**Comment by landswellsong** [comment]
Can we have `Space Projects` instead of `Space_projects` in the UI though? 

Bonus (related to #21): can those strings be translated too?

**Comment by 0486** [comment]
Fixed mentioned issues. Please check.

**Comment by landswellsong** [comment]
@0486 while you're on it, please check if the plugins you test support translating `verbose_name`s

**Pull request merged**
